### ISSUE TITLE
Define where we want to be hosted in slack

### ISSUE THREAD

**Issue by MalloZup** [remotomic/community#1]
I think having a slack channel would be quite good.

We need eventually to find a workspace where to be hosted:

CNCF could be an opportunity.

Are there any others, more generic?

**Comment by saschagrunert** [comment]
Hm, it should be a slack which has already a nice set of members. We could hook into the k8s.io one which is pretty large. But it seems too narrow scoped.

**Comment by MalloZup** [comment]
Yes. I am considering also to add temporally a gutter channel for the repo

**Comment by MalloZup** [comment]
I think K8s is somehow for me to constraint @krig do you know some sort of slack ch

**Comment by krig** [comment]
no, I am not a huge slack user..

**Comment by MalloZup** [comment]
I think slack or any chat medium can be OK. It is not a requirement slack

**Comment by MalloZup** [comment]
I'm closing this more or less because the thing is more IRC/VIDEO
