### ISSUE TITLE
logo for this org

### ISSUE THREAD

**Issue by MalloZup** [remotomic/community#2]
Design a logo with following images/keyword:

- remote (people working from different places)
- connection/help
- quality talks
- functional programming values (atomic)
- galaxy/universe.

@Tobaloidee cc if you are interested :rocket:

**Comment by MalloZup** [comment]
@saschagrunert  as avatar I have updated an experimental one, :grin:  if you don't like it feel free to propose a new one. It is as personal picture of my dog so there is not copyright on it :grin:

**Comment by saschagrunert** [comment]
Hehe, don’t you have any designer at hand which could help us here?

**Comment by MalloZup** [comment]
for moment not. :grin:
